[jev]
filename = jev.py
chunked = true
python.version = python3
python.required = 3.9, 3.13
is_risky = false
run_in_preview = false

[jevtest]
filename = jevtest.py
chunked = true
python.version = python3
python.required = 3.9, 3.13
is_risky = false
run_in_preview = false
